- route:
    from:
      uri: platform-http:/price
      steps:
        - removeHeaders:
            pattern: "*"
        - to:
            uri: http://lab-tf-server:8501/v1/models/redbag:predict
        
        - unmarshal:
            json: {}
        
        - setHeader:
            name: product
            expression:
              simple:
                expression: ${body[predictions][0]}
        
        - to:
            uri: language:constant:resource:classpath:price-catalogue.json
        
        - setBody:
            expression:
              jq:
                expression: .[] | select(.item == header("product")).price
                resultType: String
        
        - setBody:
            expression:
              simple:
                expression: '{"price": "${body}"}'
        
        - log:
            message: result is ${body}
